// Construit plugins/text-editor/hljs.js : highlight.js (core + langages choisis)
// en un seul fichier navigateur. Depuis le dépôt allkin (où highlight.js est installé) :
//   node_modules/.bin/esbuild ../allkin-plugins/scripts/hljs-entry.mjs --bundle --format=iife --minify --target=es2019 --legal-comments=none --outfile=../allkin-plugins/plugins/text-editor/hljs.js
import hljs from "../../allkin/node_modules/highlight.js/lib/core.js";
import l1 from "../../allkin/node_modules/highlight.js/lib/languages/javascript.js"; hljs.registerLanguage("javascript", l1);
import l2 from "../../allkin/node_modules/highlight.js/lib/languages/typescript.js"; hljs.registerLanguage("typescript", l2);
import l3 from "../../allkin/node_modules/highlight.js/lib/languages/json.js"; hljs.registerLanguage("json", l3);
import l4 from "../../allkin/node_modules/highlight.js/lib/languages/css.js"; hljs.registerLanguage("css", l4);
import l5 from "../../allkin/node_modules/highlight.js/lib/languages/scss.js"; hljs.registerLanguage("scss", l5);
import l6 from "../../allkin/node_modules/highlight.js/lib/languages/less.js"; hljs.registerLanguage("less", l6);
import l7 from "../../allkin/node_modules/highlight.js/lib/languages/xml.js"; hljs.registerLanguage("xml", l7);
import l8 from "../../allkin/node_modules/highlight.js/lib/languages/markdown.js"; hljs.registerLanguage("markdown", l8);
import l9 from "../../allkin/node_modules/highlight.js/lib/languages/yaml.js"; hljs.registerLanguage("yaml", l9);
import l10 from "../../allkin/node_modules/highlight.js/lib/languages/bash.js"; hljs.registerLanguage("bash", l10);
import l11 from "../../allkin/node_modules/highlight.js/lib/languages/shell.js"; hljs.registerLanguage("shell", l11);
import l12 from "../../allkin/node_modules/highlight.js/lib/languages/python.js"; hljs.registerLanguage("python", l12);
import l13 from "../../allkin/node_modules/highlight.js/lib/languages/php.js"; hljs.registerLanguage("php", l13);
import l14 from "../../allkin/node_modules/highlight.js/lib/languages/php-template.js"; hljs.registerLanguage("php-template", l14);
import l15 from "../../allkin/node_modules/highlight.js/lib/languages/ini.js"; hljs.registerLanguage("ini", l15);
import l16 from "../../allkin/node_modules/highlight.js/lib/languages/sql.js"; hljs.registerLanguage("sql", l16);
import l17 from "../../allkin/node_modules/highlight.js/lib/languages/pgsql.js"; hljs.registerLanguage("pgsql", l17);
import l18 from "../../allkin/node_modules/highlight.js/lib/languages/c.js"; hljs.registerLanguage("c", l18);
import l19 from "../../allkin/node_modules/highlight.js/lib/languages/cpp.js"; hljs.registerLanguage("cpp", l19);
import l20 from "../../allkin/node_modules/highlight.js/lib/languages/csharp.js"; hljs.registerLanguage("csharp", l20);
import l21 from "../../allkin/node_modules/highlight.js/lib/languages/java.js"; hljs.registerLanguage("java", l21);
import l22 from "../../allkin/node_modules/highlight.js/lib/languages/kotlin.js"; hljs.registerLanguage("kotlin", l22);
import l23 from "../../allkin/node_modules/highlight.js/lib/languages/swift.js"; hljs.registerLanguage("swift", l23);
import l24 from "../../allkin/node_modules/highlight.js/lib/languages/go.js"; hljs.registerLanguage("go", l24);
import l25 from "../../allkin/node_modules/highlight.js/lib/languages/rust.js"; hljs.registerLanguage("rust", l25);
import l26 from "../../allkin/node_modules/highlight.js/lib/languages/ruby.js"; hljs.registerLanguage("ruby", l26);
import l27 from "../../allkin/node_modules/highlight.js/lib/languages/perl.js"; hljs.registerLanguage("perl", l27);
import l28 from "../../allkin/node_modules/highlight.js/lib/languages/lua.js"; hljs.registerLanguage("lua", l28);
import l29 from "../../allkin/node_modules/highlight.js/lib/languages/dart.js"; hljs.registerLanguage("dart", l29);
import l30 from "../../allkin/node_modules/highlight.js/lib/languages/scala.js"; hljs.registerLanguage("scala", l30);
import l31 from "../../allkin/node_modules/highlight.js/lib/languages/haskell.js"; hljs.registerLanguage("haskell", l31);
import l32 from "../../allkin/node_modules/highlight.js/lib/languages/elixir.js"; hljs.registerLanguage("elixir", l32);
import l33 from "../../allkin/node_modules/highlight.js/lib/languages/erlang.js"; hljs.registerLanguage("erlang", l33);
import l34 from "../../allkin/node_modules/highlight.js/lib/languages/r.js"; hljs.registerLanguage("r", l34);
import l35 from "../../allkin/node_modules/highlight.js/lib/languages/julia.js"; hljs.registerLanguage("julia", l35);
import l36 from "../../allkin/node_modules/highlight.js/lib/languages/matlab.js"; hljs.registerLanguage("matlab", l36);
import l37 from "../../allkin/node_modules/highlight.js/lib/languages/powershell.js"; hljs.registerLanguage("powershell", l37);
import l38 from "../../allkin/node_modules/highlight.js/lib/languages/dockerfile.js"; hljs.registerLanguage("dockerfile", l38);
import l39 from "../../allkin/node_modules/highlight.js/lib/languages/nginx.js"; hljs.registerLanguage("nginx", l39);
import l40 from "../../allkin/node_modules/highlight.js/lib/languages/apache.js"; hljs.registerLanguage("apache", l40);
import l41 from "../../allkin/node_modules/highlight.js/lib/languages/makefile.js"; hljs.registerLanguage("makefile", l41);
import l42 from "../../allkin/node_modules/highlight.js/lib/languages/cmake.js"; hljs.registerLanguage("cmake", l42);
import l43 from "../../allkin/node_modules/highlight.js/lib/languages/diff.js"; hljs.registerLanguage("diff", l43);
import l44 from "../../allkin/node_modules/highlight.js/lib/languages/http.js"; hljs.registerLanguage("http", l44);
import l45 from "../../allkin/node_modules/highlight.js/lib/languages/protobuf.js"; hljs.registerLanguage("protobuf", l45);
import l46 from "../../allkin/node_modules/highlight.js/lib/languages/latex.js"; hljs.registerLanguage("latex", l46);
import l47 from "../../allkin/node_modules/highlight.js/lib/languages/vim.js"; hljs.registerLanguage("vim", l47);
import l48 from "../../allkin/node_modules/highlight.js/lib/languages/plaintext.js"; hljs.registerLanguage("plaintext", l48);
import l49 from "../../allkin/node_modules/highlight.js/lib/languages/properties.js"; hljs.registerLanguage("properties", l49);
import l50 from "../../allkin/node_modules/highlight.js/lib/languages/objectivec.js"; hljs.registerLanguage("objectivec", l50);
import l51 from "../../allkin/node_modules/highlight.js/lib/languages/groovy.js"; hljs.registerLanguage("groovy", l51);
import l52 from "../../allkin/node_modules/highlight.js/lib/languages/gradle.js"; hljs.registerLanguage("gradle", l52);
import l53 from "../../allkin/node_modules/highlight.js/lib/languages/awk.js"; hljs.registerLanguage("awk", l53);
import l54 from "../../allkin/node_modules/highlight.js/lib/languages/vbscript.js"; hljs.registerLanguage("vbscript", l54);
import l55 from "../../allkin/node_modules/highlight.js/lib/languages/x86asm.js"; hljs.registerLanguage("x86asm", l55);
import l56 from "../../allkin/node_modules/highlight.js/lib/languages/arduino.js"; hljs.registerLanguage("arduino", l56);
import l57 from "../../allkin/node_modules/highlight.js/lib/languages/django.js"; hljs.registerLanguage("django", l57);
import l58 from "../../allkin/node_modules/highlight.js/lib/languages/handlebars.js"; hljs.registerLanguage("handlebars", l58);
import l59 from "../../allkin/node_modules/highlight.js/lib/languages/twig.js"; hljs.registerLanguage("twig", l59);
import l60 from "../../allkin/node_modules/highlight.js/lib/languages/coffeescript.js"; hljs.registerLanguage("coffeescript", l60);
import l61 from "../../allkin/node_modules/highlight.js/lib/languages/clojure.js"; hljs.registerLanguage("clojure", l61);
import l62 from "../../allkin/node_modules/highlight.js/lib/languages/lisp.js"; hljs.registerLanguage("lisp", l62);
import l63 from "../../allkin/node_modules/highlight.js/lib/languages/scheme.js"; hljs.registerLanguage("scheme", l63);
import l64 from "../../allkin/node_modules/highlight.js/lib/languages/ocaml.js"; hljs.registerLanguage("ocaml", l64);
import l65 from "../../allkin/node_modules/highlight.js/lib/languages/fsharp.js"; hljs.registerLanguage("fsharp", l65);
import l66 from "../../allkin/node_modules/highlight.js/lib/languages/elm.js"; hljs.registerLanguage("elm", l66);
import l67 from "../../allkin/node_modules/highlight.js/lib/languages/crystal.js"; hljs.registerLanguage("crystal", l67);
import l68 from "../../allkin/node_modules/highlight.js/lib/languages/nim.js"; hljs.registerLanguage("nim", l68);
import l69 from "../../allkin/node_modules/highlight.js/lib/languages/d.js"; hljs.registerLanguage("d", l69);
import l70 from "../../allkin/node_modules/highlight.js/lib/languages/fortran.js"; hljs.registerLanguage("fortran", l70);
import l71 from "../../allkin/node_modules/highlight.js/lib/languages/basic.js"; hljs.registerLanguage("basic", l71);
import l72 from "../../allkin/node_modules/highlight.js/lib/languages/vbnet.js"; hljs.registerLanguage("vbnet", l72);
import l73 from "../../allkin/node_modules/highlight.js/lib/languages/delphi.js"; hljs.registerLanguage("delphi", l73);
import l74 from "../../allkin/node_modules/highlight.js/lib/languages/prolog.js"; hljs.registerLanguage("prolog", l74);
import l75 from "../../allkin/node_modules/highlight.js/lib/languages/haxe.js"; hljs.registerLanguage("haxe", l75);
import l76 from "../../allkin/node_modules/highlight.js/lib/languages/tcl.js"; hljs.registerLanguage("tcl", l76);
import l77 from "../../allkin/node_modules/highlight.js/lib/languages/smalltalk.js"; hljs.registerLanguage("smalltalk", l77);
import l78 from "../../allkin/node_modules/highlight.js/lib/languages/dns.js"; hljs.registerLanguage("dns", l78);
import l79 from "../../allkin/node_modules/highlight.js/lib/languages/ldif.js"; hljs.registerLanguage("ldif", l79);
import l80 from "../../allkin/node_modules/highlight.js/lib/languages/accesslog.js"; hljs.registerLanguage("accesslog", l80);
hljs.registerAliases(["html","htm","svg","vue","xhtml","plist"], { languageName: "xml" });
hljs.registerAliases(["toml","cfg","conf","editorconfig","gitconfig"], { languageName: "ini" });
hljs.registerAliases(["zsh","env","sh"], { languageName: "bash" });
hljs.registerAliases(["txt","text","log"], { languageName: "plaintext" });
hljs.registerAliases(["mjs","cjs","jsx"], { languageName: "javascript" });
hljs.registerAliases(["tsx","mts","cts"], { languageName: "typescript" });
hljs.registerAliases(["yml"], { languageName: "yaml" });
hljs.registerAliases(["ps1","psm1"], { languageName: "powershell" });
hljs.registerAliases(["docker","Dockerfile"], { languageName: "dockerfile" });
hljs.registerAliases(["mk"], { languageName: "makefile" });
hljs.registerAliases(["h","hpp","hh","cc","cxx"], { languageName: "cpp" });
hljs.registerAliases(["kt","kts"], { languageName: "kotlin" });
hljs.registerAliases(["rs"], { languageName: "rust" });
hljs.registerAliases(["rb","gemspec","rake"], { languageName: "ruby" });
hljs.registerAliases(["py","pyw"], { languageName: "python" });
hljs.registerAliases(["pl","pm"], { languageName: "perl" });
hljs.registerAliases(["ex","exs"], { languageName: "elixir" });
hljs.registerAliases(["hs"], { languageName: "haskell" });
hljs.registerAliases(["jl"], { languageName: "julia" });
hljs.registerAliases(["m"], { languageName: "objectivec" });
hljs.registerAliases(["tex"], { languageName: "latex" });
hljs.registerAliases(["patch"], { languageName: "diff" });
hljs.registerAliases(["gql"], { languageName: "graphql" });
hljs.registerAliases(["proto"], { languageName: "protobuf" });
hljs.registerAliases(["md","markdown"], { languageName: "markdown" });
hljs.registerAliases(["cs"], { languageName: "csharp" });
hljs.registerAliases(["fs","fsx"], { languageName: "fsharp" });
hljs.registerAliases(["clj","cljs","edn"], { languageName: "clojure" });
hljs.registerAliases(["ml","mli"], { languageName: "ocaml" });
hljs.registerAliases(["nginxconf"], { languageName: "nginx" });
hljs.registerAliases(["apacheconf","htaccess"], { languageName: "apache" });
hljs.registerAliases(["hbs"], { languageName: "handlebars" });
hljs.registerAliases(["coffee"], { languageName: "coffeescript" });
hljs.registerAliases(["asm","s"], { languageName: "x86asm" });
hljs.registerAliases(["ino"], { languageName: "arduino" });
hljs.registerAliases(["pas"], { languageName: "delphi" });
hljs.registerAliases(["f","f90","f95"], { languageName: "fortran" });
hljs.registerAliases(["cob","cbl"], { languageName: "cobol" });
hljs.registerAliases(["vb"], { languageName: "vbnet" });
hljs.registerAliases(["vbs"], { languageName: "vbscript" });
hljs.registerAliases(["scm","ss"], { languageName: "scheme" });
hljs.registerAliases(["lsp","el"], { languageName: "lisp" });
window.AllkinHljs = hljs;
